global:
  storageClass:  "standard"
persistence:
  persistentVolumeClaim:
    database:
      size: 1024Gi
tls:
  secretName: tls-secret
externalURL: https://harbor.ashburncloud.net
harborAdminPassword: admin
ingress:
  hosts:
    core: harbor.ashburncloud.net
    notary: notary.ashburncloud.net
  enabled: true
service:
  tls:
    commonName: harbor.ashburncloud.net
